### ISSUE TITLE
Error when trying to authenticate

### ISSUE THREAD

**Issue by davefrassoni** [anagramik/laravel-swiftdil-api-wrapper#1]
I'm getting an error when trying to authenticate, maybe someone can help?

**Call to undefined method ErrorException::getResponse()**
```
..vendor\anagramik\laravel-swiftdil-api\src\Authenticate.php

    private function loadMessageFromException($e)
    {
        $message = json_decode($e->getResponse()->getBody()->getContents());
 
        if (empty($message)) {
 
            $message = $e->getResponse()->getReasonPhrase();
        }
 
        return $message;
    }
```

I already checked **API Client ID** and **API Client Key** and **URL** and are correct. All this is using sandbox.

**Comment by anagramik** [comment]
Hey man :) They never approved my sandbox account so I never tested this properly and I have stopped working on it. You probably need to form repo and edit Authenticate class

**Comment by anagramik** [comment]
@davefrassoni I think I just fucked up try/catch in Authenticate class line 37. You just need use GuzzleHttp\Exception\RequestException instead of \Exception

**Comment by anagramik** [comment]
I have updated it so you can just reinstall it
